[#257] Code Overhaul
amosyu2000/cyclops pull request #258
Opened 2023-02-25 01:42 UTC by MannyLemos

2023-02-25 03:14 UTC, amosyu2000 requested changes

2023-02-25 03:14 UTC, amosyu2000 commented on src/__main__.py
> -os.system("sudo poweroff")
supposed to uncomment this?

2023-02-25 03:14 UTC, amosyu2000 commented on src/csv_handler/__init__.py
> +	def __init__(self, filename, temp_dir):
Should update function description if you add another parameter

2023-03-01 17:44 UTC, briantule approved these changes
Nice

2023-03-01 18:59 UTC, amoscheung99527 approved these changes

2023-03-02 16:12 UTC, merged