Dev plan
amosyu2000/cyclops pull request #32
Opened 2022-09-23 17:57 UTC by briantule

Created the development plan as a md. Please take a look and comment any topics I have missed. Otherwise, the file can be updated for later revisions.

2022-09-23 18:39 UTC, amosyu2000 requested changes
Nice work! Please also delete the DevelopmentPlan.tex and DevelopmentPlan.pdf files.

2022-09-23 19:36 UTC, amosyu2000 reviewed
Could you also please include the issue number  in at least one of the commit messages?

2022-09-23 21:50 UTC, amoscheung99527 commented on docs/DevelopmentPlan/DevelopmentPlan.md
> +Team members are are expected to use the private Github repository. Team members will also be expected to maintain repos containing clean and accurate code. Members will are required to create new br
there's an extra "are" in "Team members are are".
"Members will are required" also has an extra "are"

2022-09-24 14:25 UTC, MannyLemos requested changes
Under 'Roles and Responsibilities' -> 'Manny Lemos'
censor should be spelt sensor

2022-09-24 22:32 UTC, MannyLemos approved these changes
good

2022-09-24 22:35 UTC, amoscheung99527 approved these changes
nice job!

2022-09-24 23:06 UTC, amosyu2000 approved these changes
LGTM! Are you gonna squash merge or rebase merge?

2022-09-25 00:53 UTC, briantule commented
Was gonna rebase merge. Wassup

2022-09-25 03:51 UTC, merged